# we're not using this but i keep it around in case i add browser-sync
PORT: 3000

# autoprefixer will make sure your CSS works with these browsers
COMPATIBILITY:
  - "last 2 versions"
  - "ie >= 9"

# uncss will use these settings
UNCSS_OPTIONS:
  html:
    - "src/pages/*.html"
  ignore:
    - !!js/regexp ^\.is-.*

# gulp will reference these paths when it copies files
PATHS:
  # path to dist folder
  dist: "dist"  
  # paths to static assets that aren't images, css, or js
  assets:
    - "!src/assets/{img,js,scss}/**/*"
    - "src/assets/*.ico"
  # regular css files that aren't sass, less, etc
  css:
    - "src/css/*.css"
  # paths to sass libraries, which can then be loaded with @import
  sass:
    - "src/scss/*.scss"
  # paths to non-react js files/libraries, which are compined into one file
  javascript:
    - "src/js/*.js"
    - "src/js/*.min.js"