# Your project's server will run on localhost:xxxx at this port
PORT: 8000

# Autoprefixer will make sure your CSS works with these browsers
COMPATIBILITY:
  - "last 2 versions"
  - "ie >= 9"

# UnCSS will use these settings
UNCSS_OPTIONS:
  html:
    - "src/pages/*.html"
  ignore:
    - !!js/regexp ^\.is-.*

# Gulp will reference these paths when it copies files
PATHS:
  # Path to dist folder
  dist: "dist"  
  # Paths to static assets that aren't images, CSS, or JavaScript
  assets:
    - "!src/assets/{img,js,scss}/**/*"
    - "src/assets/*.ico"
  # Paths to Sass libraries, which can then be loaded with @import
  sass:
    - "src/scss/*.scss"
  # Paths to JavaScript libraries, which are compined into one file
  javascript:
    - "src/static_js/*.js"